### ISSUE TITLE
Why is just-js in the top 2 of techempower?

### ISSUE THREAD

**Issue by rishavs** [justjs/just#5]
Hi

Just saw the [latest update of techempower](https://www.techempower.com/benchmarks/#section=test&runid=9716e3cd-9e53-433c-b6c5-d2c48c9593c1&hw=ph&test=composite&a=2) and I am very confused as to how a javascript framework is in top 2, beating pretty much every well established toolset/language out there.

I couldn't find any writeup on what just-js is doing different here. Even the number of stars on your project (4 as of now) seems insane, given the kind of performance this framework shows in the benchmark.

Is there something I am missing?
I would love to understand what is the secret sauce here for the benchmark numbers. 
As there doesn't seems to be a blog, article or anything on just-js, I hope you would explain something about this framework and why it seems to be topping the benchmarks?

**Comment by rishavs** [comment]
I am an idiot. Closing this as this is the wrong just-js repo.
Sorry to be a bother.

**Comment by billywhizz** [comment]
Hi @rishavs. This is the correct repo. I am the maintainer of just-js. Is kind of in stealth mode at moment. Still a lot of things I need to work on and little time. I am working on a blog post about this. Should be done in a couple of days and will update here when I get a chance. Feel free to re-open the issue.

**Comment by billywhizz** [comment]
hi @rishavs . this is the project you are looking for. feel free to DM me if easier or raise an issue on there. thx https://github.com/just-js/just
